#!/bin/bash
# Version 1.1-Alpha

docker stop seededdb
docker stop archangelui
docker stop archangelms

docker rmi -f $(docker images | grep 'archangeldb' | awk '{print $3}')
docker rmi -f $(docker images | grep 'archangelui' | awk '{print $3}')
docker rmi -f $(docker images | grep 'archangelms' | awk '{print $3}')

cwd=$(pwd)

mvn clean package

echo "creating the archangelui (Web UI) Image"
cd $cwd
cd archangelui/docker
docker build --tag archangelui .

echo "creating the archangelms (Microservice) Image"
cd $cwd
cd archangelms/docker
docker build --tag archangelms .

echo "creating the archangeldb (MongoDB preloaded data) Image"

cd $cwd
cd archangeldb/docker
docker build --tag archangeldb .

xhost=`hostname --ip-address`

echo ">>> The ArchAngel is now online"
echo "http://$xhost:10080"
