#!/bin/bash


#if [ -d "ArchAngel" ]; then
#  echo "DIRECTORY EXISTS, exiting"
#  exit -1
#fi


cwd=`pwd`
clean=0
start=0

for arg in "$@"
do
    if [[ "x$arg" == "xstart" ]];
    then
        echo "...Application will be started upon successful build..."
	start=1
    elif [[ "x$arg" == "xclean" ]];
    then
        echo "... Old images will be removed"
	echo "bringing the system offline ... docker-compose down"
	docker-compose down
        clean=1
    fi
done

echo "BUILDING ArchangeDB"
if [[ $clean == 1 ]]; then
	echo "cleaning archangeldb containers & images"
	docker stop archangeldb
	docker rm archangeldb
	docker rmi -f archangeldb
	docker rmi -f $(docker images | grep 'archangeldb' | awk '{print $3}')
fi

#kill -9 $(ps -ef | grep '[a]rchAngelService.jar' | awk '{print $2}')
#kill -9 $(ps -ef | grep '[a]rchAngelFrontEnd.jar' | awk '{print $2}')
#rm -rf .extract
#rm -rf frontend/.extract
#rm -rf service/.extract

cd $cwd/archangeldb/docker
docker build --tag archangeldb .

echo "BUILDING ArchangeMS"
if [[ $clean == 1 ]]; then
        echo "cleaning archangelms images"
	docker stop archangelms
	docker rm archangelms
	docker rmi -f archangelms
	docker rmi -f $(docker images | grep 'archangelms' | awk '{print $3}')
fi
cd $cwd/archangelms
rm -rf docker/*.jar
mvn clean package
cd docker/
cp ../target/archAngelService.jar .
docker build --tag archangelms .


echo "BUILDING ArchangeUI"
if [[ $clean == 1 ]]; then
        echo "cleaning archangelui images"
	docker stop archangelui
	docker rm archangelui
	docker rmi -f archangelui
	docker rmi -f $(docker images | grep 'archangelui' | awk '{print $3}')
fi
cd $cwd/archangelui
rm -rf docker/*.jar
mvn clean package
cd docker
cp ../target/archAngelFrontEnd.jar .
docker build --tag archangelui .


if [[ $start == 1 ]]; then
	echo "Application Built, starting application vai: docker-compose up -d"
	cd $cwd/archangelui
	docker-compose up -d
else
	echo "Application Built, you can start the system by executing: docker-compose up -d"
 fi




